services:
  # Bazarr - Subtitle Management
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["media", "starr", "all"]
    networks:
      - default
    ports:
      - "$BAZARR_PORT:6767"
    volumes:
      - $DOCKERDIR/appdata/bazarr:/config
      - $MEDIADIR:/data/media
      # - $MEDIADIR2:/data/media2
      # - $MEDIADIR3:/data/media3
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
