services:
  # File Browser - Explorer
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - "$FILEBROWSER_PORT:80"
    volumes:
      - $DOCKERDIR/appdata/filebrowser:/config
      - $USERDIR:/data/home
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - homepage.group=Tools
      - homepage.name=File Browser
      - homepage.icon=files.png
      - homepage.href=http://${HOST_IP}:${FILEBROWSER_PORT}
      - homepage.description=Web File Manager
      - homepage.widget.type=filebrowser
      - homepage.widget.url=http://${HOST_IP}:${FILEBROWSER_PORT}
      - homepage.widget.username=${FILEBROWSER_USERNAME}
      - homepage.widget.password=${FILEBROWSER_PASSWORD}
      - homepage.widget.authHeader=X-My-Header
          # username: username
          # password: password
          # authHeader: X-My-Header # If using Proxy header authentication