services:
  # FlareSolverr - Anti-Captcha Service
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
      - socket_proxy
    ports:
      - "$FLARESOLVERR_PORT:8191"
    volumes:
      - $DOCKERDIR/appdata/flaresolverr:/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    # labels:
    #   - homepage.group=Tools
    #   - homepage.name=FlareSolverr
    #   - homepage.icon=flaresolverr.png
    #   - homepage.href=http://${HOST_IP}:${FLARESOLVERR_PORT}
    #   - homepage.description=Anti-Captcha Service
