services:
  # Plex - Media Server
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["media", "all"]
    networks:
      - default
    ports:
      - "$PLEX_PORT:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    devices:
      - /dev/dri:/dev/dri # for hardware transcoding
    volumes:
      - $DOCKERDIR/appdata/plex:/config
      - $DOWNLOADSDIR:/data/downloads
      - $MEDIADIR:/data/media
      # - $MEDIADIR2:/data/media2 # Extra Media Folder
      # - $MEDIADIR3:/data/media3 # Extra Media Folder
      - /dev/shm:/data/transcode # Offload transcoding to RAM if you have enough RAM
    environment:
      TZ: $TZ
      HOSTNAME: $PLEX_SERVER_NAME
      PLEX_CLAIM_FILE: /run/secrets/plex_claim # Not required initially
      PLEX_UID: $PUID
      PLEX_GID: $PGID
      ADVERTISE_IP: "http://$SERVER_LAN_IP:32400/"
      ALLOWED_NETWORKS: $LOCAL_IPS
    secrets:
      - plex_claim
    labels:
      - homepage.group=Media
      - homepage.name=Plex
      - homepage.icon=plex.png
      - homepage.href=http://${HOST_IP}:${PLEX_PORT}/web
      - homepage.description=Media Server
      # - homepage.widget.type=plex
      # - homepage.widget.url=http://${HOST_IP}:${PLEX_PORT}
      # - homepage.widget.key=${PLEX_API_KEY}
      # - homepage.widget.fields="streams" "movies" "tv" "albums"
