services:
  # Portainer - WebUI for Containers
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - default
      - socket_proxy
    # command: -H unix:///var/run/docker.sock # Use Docker Socket Proxy instead for improved security
    command: -H tcp://socket-proxy:2375
    ports:
      - "$PORTAINER_PORT:9000"
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock:ro # Use Docker Socket Proxy instead for improved security
      - $DOCKERDIR/appdata/portainer/data:/data
    environment:
      - TZ=$TZ
    labels:
      - homepage.group=Tools
      - homepage.name=Portainer
      - homepage.icon=portainer.png
      - homepage.href=http://${HOST_IP}:${PORTAINER_PORT}
      - homepage.description=Container Management
      - homepage.widget.type=portainer
      - homepage.widget.url=http://${HOST_IP}:${PORTAINER_PORT}
      - homepage.widget.key=${PORTAINER_API_KEY}
      - homepage.widget.env=1