services:
  # Prowlarr - Index Manager
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "starr", "all"]
    networks:
      - default
    ports:
      - "$PROWLARR_PORT:9696"
    volumes:
      - $DOCKERDIR/appdata/prowlarr:/config
      - $DOWNLOADSDIR:/data/downloads
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    # DOCKER-LABELS-PLACEHOLDER

    labels:
      - homepage.group=Starr
      - homepage.name=Prowlarr
      - homepage.icon=prowlarr.png
      - homepage.href=http://${HOST_IP}:${PROWLARR_PORT}
      - homepage.description=Index Manager
      - homepage.widget.type=prowlarr
      - homepage.widget.url=http://${HOST_IP}:${PROWLARR_PORT}
      - homepage.widget.key=${PROWLARR_API_KEY}