services:
  # SABnzbd - Binary newsgrabber (NZB downloader)
  # Disable SABNnzbd's built-in HTTPS support for traefik proxy to work
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "downloads", "all"]
    networks:
      - default
    ports:
      - "$SABNZBD_PORT:8080"
    volumes:
      - $DOCKERDIR/appdata/sabnzbd:/config
      - $DOWNLOADSDIR:/data/downloads
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      UMASK: 002
    labels:
      - traefik.enable=true
      - traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.${LOCAL_DOMAIN}`)
      - traefik.http.routers.sabnzbd.entrypoints=web
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8080
